#!/bin/bash
set -o errexit

STAGED_JS=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.jsx" "*.json" |
    sed 's| |\\ |g')
STAGED_CSS=$(git diff --cached --name-only --diff-filter=ACMR "*.css" |
    sed 's| |\\ |g')

if [[ -n "${STAGED_JS}" ]]; then
    echo "$STAGED_JS" | xargs -P8 -I{} just format {}
    echo "$STAGED_JS" | xargs -P8 -I{} just lint {}
    echo "$STAGED_JS" | xargs git add

elif [[ -n "${STAGED_CSS}" ]]; then
    echo "$STAGED_CSS" | xargs -P8 -I{} just format {}
    echo "$STAGED_CSS" | xargs git add
fi

set +o errexit
exit 0
