#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.jsx" "*.json" "*.css" |
    sed 's| |\\ |g')
[ -z "$STAGED_FILES" ] && exit 0

if [[ -n "${STAGED_FILES}" ]]; then
    set -o errexit

    # format/lint everything
    echo "$STAGED_FILES" | xargs -P8 -I{} just format {}
    echo "$STAGED_FILES" | xargs -P8 -I{} just lint {}

    # Add them back to staging so that the changes get committed
    echo "$STAGED_FILES" | xargs git add

    set +o errexit
fi
